---
- name: Create mysql servers
  hosts: localhost
  tasks:

    - name: Create mysql1
      command: >
        openstack server create
        --flavor medium
        --image UbuntuJammy2204-Desktop
        --nic net-id=8d63d0cf-bafb-4ec0-9ca5-ccccf82bf740,v4-fixed-ip="192.168.1.4"
        --key-name deploy
        cannon1

    - name: Create mysql2
      command: >
        openstack server create
        --flavor medium 
        --image UbuntuJammy2204-Desktop
        --nic net-id=8d63d0cf-bafb-4ec0-9ca5-ccccf82bf740,v4-fixed-ip="192.168.2.4"
        --key-name deploy 
        cannon2
